---
  - name: create admin user
    user: name=admin state=present uid=5001

  - name: remove dojo
    user: name=dojo  state=present

  - name: install tree
    yum:  name=tree  state=present

  - name: install ntp
    yum:  name=ntp   state=present

  - name: start ntp service
    service: name=ntpd state=started enabled=yes

  - name: install a list of packages
    yum:
      name: "{{ item }}"
    with_items: "{{ demolist.packages }}"
