version: '3.3'

services:

    #Wordpress
    wordpress:
        image: wordpress:latest
        external_links: 
            - mysql:db
        volumes: 
            - ./:/var/www/html
        ports:
            - "33003:80"
        restart: always
        container_name: wordpress
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: 9611974
            WORDPRESS_DB_NAME: my_project_db

networks:
    default:
        external: 
            name: my_wordpress_network
