---
#tasks file for wordpress
  - name: Create wordpress directory
    file:
      path: /opt/docker/wordpress
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: Create docker-compose file
    copy:
      src: ./docker-compose.yml
      dest: /opt/docker/wordpress/docker-compose.yml
      owner: root
      group: root
      mode: 0644

  - name: Run docker-compose up -d
    shell: docker-compose up -d
    args:
      chdir: /opt/docker/wordpress
