version: '3.7'

services:

    #Database
    db:
        image: mysql:latest
        volumes:
            - db_data:/var/lib/mysql
        ports: 
            - "1207:3306"
        restart: always
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 9611974


    #phpMyAdmin
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        container_name: phpmyadmin
        ports: 
            - "8080:80"
        environment: 
            PMA_HOST: db:3306
            MYSQL_ROOT_PASSWORD: 9611974

volumes: 
    db_data:

networks:
    default:
        external: 
            name: my_wordpress_network
