---
#tasks file for mysql
  - name: Create mysql directory
    file:
      path: /opt/mysql/docker
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: Create docker-compose file
    copy:
      src: ./docker-compose.yml
      dest: /opt/mysql/docker/docker-compose.yml
      owner: root
      group: root
      mode: 0644

  - name: Run docker-compose up -d
    shell: docker-compose up -d
    args:
      chdir: /opt/mysql/docker

