---
  - name: Application server installtion
    hosts: app
    become: true
    roles:
      - apache

  - name: Database installation
    hosts: db
    become: true
    roles:
      - mysql

  - name: Loadbalancer installation
    hosts: lb
    become: true
    roles:
      - nginxlb
