---
- name: Creating configuration from templates...
  template: src=httpd.conf.j2
            dest=/etc/httpd.conf
            owner=root group=root mode=0644
  notify: Restart apache service
- name: Copying index.html file...
  template: src=index.html.j2
        dest=/var/www/html/index.html
        mode=0777
